### ISSUE TITLE
哪位大神来翻译成oc吧！！

### ISSUE THREAD

**Issue by Joneze** [Shannon-s-Dreamland/VideoPlayer#1]
如果有oc就好了！！

**Comment by inatu** [comment]
Objective-C的项目是可以加入 Swift 的代码的, 而且要比 Objective-C 的代码的稳定性和性能要好一些, https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/ https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/
不推荐翻译成Objective-C, 比较推荐你开始学习 Swift, 并不认为 Objective-C 在以后会比 Swift 流行
